### ISSUE TITLE
Error.....  I keep getting this bind error

### ISSUE THREAD

**Issue by ldhall1856** [codetheweb/homebridge-tuya-outlet#10]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:6666
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

<img width="469" alt="error" src="https://user-images.githubusercontent.com/37450359/37685730-81e8569e-2c62-11e8-98b5-ee5dce9dc5b2.png">

**Comment by codetheweb** [comment]
That means that some other process is currently using port 6666, which TuyAPI uses for resolving device IDs to IPs.  Either try to find the conflicting process with `sudo netstat`, or pass your device's IP to `homebridge-tuya-outlet` so it doesn't try to find it.  Example config with IP:
```
{
  "accessory": "TuyaOutlet",
  "name": "Tuya Outlet",
  "ip": "192.168.0.xxx",
  "devId": "xxxxxxxxxxxxxxxxxxx",
  "localKey": "xxxxxxxxxxxxxxx"
}
```
