### ISSUE TITLE
Plugin stops homebridge from loading

### ISSUE THREAD

**Issue by blloyd78** [codetheweb/homebridge-tuya-outlet#12]
I recently upgraded the nodejs instance on my Raspberry Pi and the soundtouch plugins no longer work. I receive the following error on start-up:

```
/usr/local/lib/node_modules/homebridge/lib/api.js:64
homebridge_1  |       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
homebridge_1  |             ^
homebridge_1  | Error: The requested accessory 'SoundTouch' was not registered by any plugin.
```

A dig through the logs shows:

```
[2018-3-23 16:13:55] ERROR LOADING PLUGIN homebridge-soundtouch:
homebridge_1  | [2018-3-23 16:13:55] Error: Cannot find module '../build/Release/dns_sd_bindings'
homebridge_1  |     at Function.Module._resolveFilename (module.js:547:15)
homebridge_1  |     at Function.Module._load (module.js:474:25)
homebridge_1  |     at Module.require (module.js:596:17)
homebridge_1  |     at require (internal/module.js:11:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
homebridge_1  |     at Module._compile (module.js:652:30)
homebridge_1  |     at Object.Module._extensions..js (module.js:663:10)
homebridge_1  |     at Module.load (module.js:565:32)
homebridge_1  |     at tryModuleLoad (module.js:505:12)
homebridge_1  |     at Function.Module._load (module.js:497:3)
homebridge_1  |     at Module.require (module.js:596:17)
homebridge_1  |     at require (internal/module.js:11:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/mdns/lib/mdns.js:1:77)
homebridge_1  |     at Module._compile (module.js:652:30)
homebridge_1  |     at Object.Module._extensions..js (module.js:663:10)
homebridge_1  |     at Module.load (module.js:565:32)
```

Note. This Homebridge instance is running as a Docker container if that makes any difference.

**Comment by codetheweb** [comment]
I think you meant to open this issue at the [homebridge-soundtouch](https://github.com/CONNCTED/homebridge-soundtouch) repo.

I've seen this error before and it usually is caused by the mDNS bindings not being installed correctly.  You might want to look at [this Github issue](https://github.com/nfarina/homebridge/issues/905) for details, or consider using a prebuilt Docker container for Homebridge like [this one](https://hub.docker.com/r/oznu/homebridge/) if you're not already.

**Comment by blloyd78** [comment]
Sorry - posted in the wrong tab 👎
